// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABiv_GkLest3jh7rfraAimyiDwQvMu1BI',
    appId: '1:86227788427:web:172df6b3bc25d8d3b22a8e',
    messagingSenderId: '86227788427',
    projectId: 'chatter5-e27dc',
    authDomain: 'chatter5-e27dc.firebaseapp.com',
    storageBucket: 'chatter5-e27dc.firebasestorage.app',
    measurementId: 'G-RSCZD23VKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1fRDRysFbef4_Um_xxnl0nAEHLVGrO4w',
    appId: '1:86227788427:android:85156e3143ec4b7eb22a8e',
    messagingSenderId: '86227788427',
    projectId: 'chatter5-e27dc',
    storageBucket: 'chatter5-e27dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMOyIUUjRukDaBq5MvsRztDmfC_VJwZ_I',
    appId: '1:86227788427:ios:44c41477fb6a52e2b22a8e',
    messagingSenderId: '86227788427',
    projectId: 'chatter5-e27dc',
    storageBucket: 'chatter5-e27dc.firebasestorage.app',
    iosBundleId: 'net.poquesoft.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMOyIUUjRukDaBq5MvsRztDmfC_VJwZ_I',
    appId: '1:86227788427:ios:44c41477fb6a52e2b22a8e',
    messagingSenderId: '86227788427',
    projectId: 'chatter5-e27dc',
    storageBucket: 'chatter5-e27dc.firebasestorage.app',
    iosBundleId: 'net.poquesoft.chatter',
  );
}
